#include "codeGenDef.h"
#include <time.h>
// #include "lexer.h"
#define HASHSIZE 300


extern Hashtable non_termainals;
extern Hashtable terminals;
int no_of_lines=1000;
char** errors;
HASHSYMBOL h;
int hash_size;
FN_ENTRY functions;
int fn_size;

int main(int argc, char *argv[]) {


	// if (argc < 2) {
	// 	printf("Give command line arguments\n" );
	// 	exit(0);
	// }
	char *file = "semantic/testcase3.txt";
	clock_t start_time, end_time;
	double total_CPU_time, total_CPU_time_in_seconds;


	// initialisations

	hashInit(15);

	hashTableInit(HASHSIZE);
	GRAMMAR g = populateGrammar("grammar.txt");
	FirstFollow f = ComputeFirstAndFollowSets(g);
	PARSETABLE t = createParseTable(f, g, t);


	// printf("Size-%ld\n",sizeof(unsigned long long int));

	TREE_NODE pt = NULL;
	NODE_AstTree ast = NULL;
	h = NULL;
	int i;
	errors = (char**)malloc(sizeof(char*)*no_of_lines);
	for ( i = 0; i < no_of_lines; i++) {
		errors[i] = NULL;
	}

	while(1)
	{

		int choice;
		printf("\n0.EXIT");
        printf("\n1. Print the tokens list generated by lexer (on Console)");
        printf("\n2. Print parse tree and output errors if any (on Console)");
        printf("\n3. Print Abstract Syntax Tree and Order of Traversal (on Console)");
        printf("\n4. Display the amount of allocated memory and no. of nodes to each of parse tree and abstract syntax tree.");
        printf("\n5. Print the Symbol Table");
        printf("\n6. Print the list of global variables, their types and offsets");
        printf("\n7. Print the total memory requirement for each function");
        printf("\n8. Print the type expressions and width of globally visible record definitions");
        printf("\n9. Verify the syntactic and semantic correctness and Print total time taken by compiler (on Console)");
        printf("\n10. For producing assembly code");


        printf("\n\nEnter your choice: ");
        scanf("%d", &choice);
		if(choice == 0)
		{
			exit(0);
		}
		else if (choice == 1)
		{
			printTokens(file);
		}
		else if (choice ==2)
		{
			pt = parseInputSourceCode(file, t, f, g);

			if(invalid_prog==0) {
				printf("Program is syntactically correct\n");
			}
			// invalid_prog=0;
			traversal(g, pt);
			printf("Inorder Traversal printed\n");
			printf("\n" );
			printf("\n" );
		}else if (choice == 3){
			if (pt==NULL) {
				printf("First make Parse tree\n" );
				continue;
			}

			ast = buildAST(pt);
			printf("\n");
			printf("--------AST POSTORDER Traveral-------\n");
			traverseAST(ast);
			printf("\n");
			printf("\n");
		}else if(choice == 4){
			if (ast == NULL) {
				printf("First make AST with option 3\n");
				continue;
			}

			h = populateSymbolTable(ast);

			int nAst = countNodesAST(ast);
			int nPt = countNodesParseTree(pt);

			printf("Number of Nodes in parsetree: %d\t",nPt);
			printf("Memory Allocated for Parse Tree: %ld\n",sizeof(TREE_NODE)*nPt );
			printf("Number of Nodes in Ast: %d\t\t",nAst);
			printf("Memory Allocated for Abstract Syntax Tree: %ld\n",sizeof(NODE_AstTree)*nAst );
			printf("\n" );
			printf("Compression Ratio: %.2f\n",(1-((float)nAst/nPt))*100 );

		}else if(choice == 5){
			if (h == NULL) {
				printf("First populate symbol table using option 4\n");
				continue;
			}
			// print symbol table in appropraite format
			printSymbolTable(record_table);
            printSymbolTable(global_table);

            NODE_AstTree temp = ast->child;
            while(temp!=NULL){

              int x;
              if(temp->tokens==NULL) {
                x = getFunction("_main");
                //printf("ma%d\n",x);
              } else {
                x = getFunction(temp->tokens->tk->lexeme);
               // printf("fun%d\n",x);
              }
//              printf("asdasa\n");
              FN_ENTRY f = functions+x;
              printSymbolTable(f->st);
              temp=temp->sibling;
            }

		}else if(choice == 6){
			// print list of all global variables
			if (h == NULL) {
				printf("First populate symbol table using option 4\n");
				continue;
			}

			SYMBOLENTRY se = global_table->head;
			while(se!=NULL) {
				printf("%s ",se->id);
				if(se->int_no==1 && se->real_no==0) {
					printf("INT ");
				} else if(se->int_no==0 && se->real_no==1) {
					printf("REAL ");
				} else {
					printf("%s ",se->record_name);
				}
				printf("%d\n",se->offset);
				se = se->next;
			}

		}else if(choice == 7){
			//For printing the total memory requirement (sum total of widths of all variables in the function scope) for each function.

			if (h == NULL) {
				printf("First populate symbol table using option 4\n");
				continue;
			}
			int temp = getFunction("_main");
			FN_ENTRY f = functions+temp;
			SYMBOLENTRY st = f->st->head;
			if(st==NULL) {
				printf("_main\t\t%d\n",0);
			} else {
				while(st->next!=NULL) {
					st=st->next;
				}
				printf("_main\t\t%d\n",st->offset+(2*st->int_no+4*st->real_no));
			}
			NODE_AstTree ns = ast->child->sibling;
			while(ns!=NULL) {
				int temp = getFunction(ns->child->tokens->tk->lexeme);
				FN_ENTRY f = functions+temp;
				SYMBOLENTRY st = f->st->head;
				if(st==NULL) {
					printf("%s\t\t0\n",ns->child->tokens->tk->lexeme);
				} else {
					while(st->next!=NULL) {
						st=st->next;
					}
					printf("%s\t\t%d\n",ns->child->tokens->tk->lexeme, st->offset+(2*st->int_no+4*st->real_no));
				}
				ns=ns->sibling;
			}

		}else if(choice == 8){
			//. For printing the type expressions and width of globally visible record definitions. Example format
			if (h == NULL) {
				printf("First populate symbol table using option 4\n");
				continue;
			}
			SYMBOLENTRY se = record_table->head;
			while(se!=NULL) {
				int x = 0;
				printf("%s\t",se->record_name);
				FIELD f = se->record;
				while(f!=NULL) {
					if(f->dType==INT) {
						x+=2;
						printf("int, ");
					} else {
						printf("real, ");
					}
					f=f->next;
				}
				printf("\t%d\n",x);
				se=se->next;
			}
		}else if(choice == 9){
			// first check syntactic errors and them semantic errors
			if (h == NULL) {
				printf("First populate symbol table using option 4\n");
				continue;
			}

			if (invalid_prog > 0) {
				printf("First remove all syntactic errors\n");
				// show syntactic errors
				pt = parseInputSourceCode(file, t, f, g);
				// printf("temp\n" );
				continue;
			}
			printf("No syntactic errors\n" );
			printf("----------Semantic_Errors---------\n" );
			semAnalyze(ast);
			printf("\n" );
			printErrors(no_of_lines);
			printf("\n" );
			printf("\n" );



		}else if(choice == 10){
			// to produce the assembly code
			codeGeneration(ast->child);
		}
		// {
		//
		// 	start_time = clock();
		//
		// 	TREE_NODE x = parseInputSourceCode(file, t, f, g);
		// 	end_time = clock();
		// 	total_CPU_time  =  (double) (end_time - start_time);
		// 	total_CPU_time_in_seconds =   total_CPU_time /
		// 	                            CLOCKS_PER_SEC;
		// 	// Print both total_CPU_time and total_CPU_time_in_seconds
		// 	printf(" Total_CPU_time_in_seconds is %.8lf\n",total_CPU_time_in_seconds);
		// 	printf("Total_CPU_time is %f\n",total_CPU_time);
		//
		// }
		else
		{
			printf("\n Invalid Choice");
		}

	}
	return 0;
}
